[env]
APP_NAME = "isded"
BIN_DIR = "bin"
BIN_APP = { source = "${CARGO_MAKE_PROFILE}", default_value = "app/target/debug/${APP_NAME}", mapping = {"development" = "app/target/debug/${APP_NAME}", "production" = "app/target/release/${APP_NAME}"} }
BIN_ENCLAVE = "enclave/enclave.signed.so"

[tasks.enclave]
command = "makers"
args = ["--cwd", "enclave"]

[tasks.app]
command = "makers"
args = ["--cwd", "app"]

[tasks.copy]
script = [
	"mkdir -p ${BIN_DIR}",
	"cp ${BIN_APP} ${BIN_DIR}/",
	"cp ${BIN_ENCLAVE} ${BIN_DIR}/"
]

[tasks.default]
clear = true
dependencies = ["enclave", "app", "copy"]

[tasks.clean]
clear = true
script = [
	"makers --cwd app clean",
	"makers --cwd enclave clean",
	"rm -rf bin"
]

