[package]
name = "selfdestructionenclave"
version = "1.0.0"
authors = ["Fuga Kato"]

[lib]
name = "selfdestructionenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.9" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.9" }
sgx_tseal = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.9" }
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.9" }

[dependencies]
#common = { path = "../common_enclave" }
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
#serde = { git = "https://github.com/mesalock-linux/serde-sgx", features = ["derive"] }
#serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx" }
chrono = { version = "0.4" }

