[package]
name = "isded"
version = "1.0.0"
authors = ["Fuga Kato"]
edition = '2018'

[lib]
name = "isded"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tprotected_fs = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", features = ["stdio"] }
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git" }
sgx_tcrypto = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git" }

[dependencies]
#common = { path = "../common_enclave" }
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
#chrono = { git = "https://github.com/mesalock-linux/chrono-sgx", default-features = false }
#failure = { git = "https://github.com/mesalock-linux/failure-sgx.git" }
#quote = "=1.0.1"
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }

[patch.'https://github.com/apache/incubator-teaclave-sgx-sdk.git']
sgx_tprotected_fs = { path = "../../../sgx_tprotected_fs" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_types = { path = "../../../sgx_types" }
sgx_tcrypto = { path = "../../../sgx_tcrypto" }

#[patch.'https://github.com/mesalock-linux/chrono-sgx']
#chrono = { path = "../../../../chrono-sgx" }
