[package]
name = "sded"
version = "1.0.0"
authors = ["Fuga Kato"]
edition = '2018'

[lib]
name = "sded"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tprotected_fs = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["stdio"] }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[dependencies]
#common = { path = "../common_enclave" }
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
chrono = { git = "https://github.com/mesalock-linux/chrono-sgx" }
failure = { git = "https://github.com/mesalock-linux/failure-sgx.git" }
quote = "=1.0.1"

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_tprotected_fs = { path = "../../../sgx_tprotected_fs" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_types = { path = "../../../sgx_types" }

