[env]
ENCLAVE = "Enclave"
ENCLAVE_EDL = "${ENCLAVE}.edl"
SGX_SDK = { value = "/opt/intel/sgxsdk", condition = { env_not_set = ["SGX_SDK"] } }
SGX_MODE = { value = "HW", condition = { env_not_set = ["SGX_MODE"] } }
SGX_ARCH = { value = "x64", condition = { env_not_set = ["SGX_ARCH"] } }
ARCH_FLAG = { source = "${SGX_ARCH}", default_value = "-m64", mapping = {"x64" = "-m64", "x86" = "-m32"} }
SGX_LIB_PATH = { source = "${SGX_ARCH}", default_value = "${SGX_SDK}/lib64", mapping = {"x64" = "${SGX_SDK}/lib64", "x86" = "${SGX_SDK}/lib"} }
RUST_SGX_SDK = { value = "../../..", condition = { env_not_set = ["RUST_SGX_SDK"] } }
OBJ_DIR = "obj"
CC = { value = "gcc", condition = { env_not_set = ["CC"] } }
CXX = { value = "g++", condition = { env_not_set = ["CXX"] } }
TRTS = { source = "${SGX_MODE}", default_value = "sgx_trts", mapping = {"HW" = "sgx_trts", "SIM" = "sgx_trts_sim"} }
TSERVICE = { source = "${SGX_MODE}", default_value = "sgx_tservice", mapping = {"HW" = "sgx_tservice", "SIM" = "sgx_tservice_sim"} }
OPT_FLAG = { source = "${CARGO_MAKE_PROFILE}", default_value = "-Og", mapping = {"development" = "-Og", "production" = "-O2"} }
DEBUG_FLAG = { value = "-g", condition = { profiles = ["development"] } }
ENCLAVE_CFLAGS = ["${ARCH_FLAG}", "${OPT_FLAG}", "-nostdinc", "-fvisibility=hidden", "-fpie", "-fstack-protector"]
ENCLAVE_INCLUDE = ["-I${RUST_SGX_SDK}/common/inc", "-I${RUST_SGX_SDK}/edl", "-I${SGX_SDK}/include", "-I${SGX_SDK}/include/tlibc", "-I${OBJ_DIR}"]
RUST_OBJ = "isded"
OUT_DIR = { source = "${CARGO_MAKE_PROFILE}", default_value = "./target/debug", mapping = {"development" = "./target/debug", "production" = "./target/release"} }
ENCLAVE_LIBS = ["-L${OUT_DIR}", "-l${RUST_OBJ}", "-l${TSERVICE}", "-lsgx_tcrypto", "-lsgx_tprotected_fs"]
ENCLAVE_LDFLAGS = ["${ARCH_FLAG}", "-Wl,--no-undefined", "-nostdlib", "-nodefaultlibs", "-nostartfiles", "-L${SGX_LIB_PATH}",
	"-Wl,--whole-archive", "-l${TRTS}", "-Wl,--no-whole-archive",
	"-Wl,--start-group", "-lsgx_tstdc", "-lsgx_tcxx", "${ENCLAVE_LIBS}", "${OBJ_DIR}/${ENCLAVE}_t.o", "-Wl,--end-group",
	"-Wl,-Bstatic", "-Wl,-Bsymbolic", "-Wl,--no-undefined",
	"-Wl,-pie,-eenclave_entry", "-Wl,--export-dynamic",
	"-Wl,--defsym,__ImageBase=0",
	"-Wl,--gc-sections",
	"-Wl,--version-script=${ENCLAVE_VERSION_SCRIPT}"]
ENCLAVE_VERSION_SCRIPT = "${ENCLAVE}.lds"
FINAL_ENCLAVE = "enclave"
KEY = "${ENCLAVE}_private.pem"

[tasks.prereq]
script = [
	"mkdir -p ${OBJ_DIR}"
]

[tasks.edger8r]
description = "Runs Edger8r to generate ${ENCLAVE}_t.{c,h}."
command = "${SGX_SDK}/bin/${SGX_ARCH}/sgx_edger8r"
args = ["--trusted",
        "--search-path", "${SGX_SDK}/include",
        "--search-path", "${RUST_SGX_SDK}/edl",
        "--trusted-dir", "${OBJ_DIR}",
        "${ENCLAVE_EDL}"]
dependencies = ["prereq"]

[tasks.Enclave_t]
description = "Compiles ${ENCLAVE}_t.o."
env = {"SRC" = "${OBJ_DIR}/${ENCLAVE}_t.c", "DEST" = "${OBJ_DIR}/${ENCLAVE}_t.o"}
command = "${CC}"
args = ["@@remove-empty(DEBUG_FLAG)", "@@split(ENCLAVE_CFLAGS,;)", "@@split(ENCLAVE_INCLUDE,;)", "-c", "-o${DEST}", "${SRC}"]
dependencies = ["edger8r"]

[tasks.build]
clear = true
description = "Compiles main component written in Rust."
env = { "RELEASE_FLAG" = { value = "--release", condition = { profiles = ["production"] } } }
command = "cargo"
args = ["build", "@@remove-empty(RELEASE_FLAG)"]
dependencies = ["edger8r"]

[tasks.link]
description = "Links all objects into ${FINAL_ENCLAVE}.so"
command = "${CXX}"
args = ["@@split(ENCLAVE_LDFLAGS,;)", "-o${FINAL_ENCLAVE}.so"]
dependencies = ["Enclave_t", "build"]

[tasks.sign]
description = "Signs the enclave."
command = "${SGX_SDK}/bin/${SGX_ARCH}/sgx_sign"
args = ["sign", "-key", "${KEY}", "-enclave", "${FINAL_ENCLAVE}.so", "-out", "${FINAL_ENCLAVE}.signed.so", "-config", "${ENCLAVE}.config.xml"]
dependencies = ["link"]

[tasks.clean]
clear = true
description = "Cleans build artifacts."
script = [
	"rm -rf ${OBJ_DIR}",
	"cargo clean"
]

[tasks.genkey]
description = "Generates new key for debugging purpose."
script = [
	"openssl genrsa -out ${KEY} -3 3072"
]

[tasks.default]
clear = true
dependencies = ["sign"]

